#!/bin/sh

echo "$@" | grep -q "macmini-m1" && {
	2>&1 echo "ssh: connect to host macmini-m1 port 22: Operation timed out"
	exit 1
}

# echo command line, quoting arguments with spaces
/usr/bin/awk 'BEGIN {
	printf "ssh"
	for (i=1; i<ARGC; i++) {
		if (index(ARGV[i], " "))
			printf " \047" ARGV[i] "\047"
		else
			printf " " ARGV[i]
	}
	printf "\n" }' "$@"
